export const BOOK_PROPERTY_NAMES = {
  title: "Title",
  sourceTitle: "Source Title",
  hakimId: "Hakim Book ID",
  asin: "ASIN",
  author: "Author",
  kindleUrl: "Kindle URL",
  lastAnnotated: "Last Annotated",
  sourceHash: "Source Hash",
  syncState: "Sync State",
  lastSynced: "Last Synced",
  highlights: "Highlights",
} as const;

export const HIGHLIGHT_PROPERTY_NAMES = {
  title: "Name",
  hakimId: "Hakim Annotation ID",
  book: "Book",
  quote: "Quote",
  kindleNote: "Kindle Note",
  locationStart: "Location Start",
  locationEnd: "Location End",
  page: "Page",
  chapter: "Chapter",
  color: "Color",
  annotatedAt: "Annotated At",
  contentLimit: "Content Limit State",
  sourceHash: "Source Hash",
  sourceState: "Source State",
  lastSynced: "Last Synced",
  processStatus: "Process Status",
  importance: "Importance",
  interpretation: "My Interpretation",
  agreement: "Agreement",
  tags: "Tags",
} as const;

export const BOOK_CORE_PROPERTIES: Record<string, unknown> = {
  [BOOK_PROPERTY_NAMES.title]: { title: {} },
  [BOOK_PROPERTY_NAMES.sourceTitle]: { rich_text: {} },
  [BOOK_PROPERTY_NAMES.hakimId]: { rich_text: {} },
  [BOOK_PROPERTY_NAMES.asin]: { rich_text: {} },
  [BOOK_PROPERTY_NAMES.author]: { rich_text: {} },
  [BOOK_PROPERTY_NAMES.kindleUrl]: { url: {} },
  [BOOK_PROPERTY_NAMES.lastAnnotated]: { date: {} },
  [BOOK_PROPERTY_NAMES.sourceHash]: { rich_text: {} },
  [BOOK_PROPERTY_NAMES.syncState]: {
    select: { options: ["Active", "Source Missing", "Confirmed Missing", "Limited"].map((name) => ({ name })) },
  },
  [BOOK_PROPERTY_NAMES.lastSynced]: { date: {} },
};

export const HIGHLIGHT_CORE_PROPERTIES: Record<string, unknown> = {
  [HIGHLIGHT_PROPERTY_NAMES.title]: { title: {} },
  [HIGHLIGHT_PROPERTY_NAMES.hakimId]: { rich_text: {} },
  [HIGHLIGHT_PROPERTY_NAMES.quote]: { rich_text: {} },
  [HIGHLIGHT_PROPERTY_NAMES.kindleNote]: { rich_text: {} },
  [HIGHLIGHT_PROPERTY_NAMES.locationStart]: { number: {} },
  [HIGHLIGHT_PROPERTY_NAMES.locationEnd]: { number: {} },
  [HIGHLIGHT_PROPERTY_NAMES.page]: { number: {} },
  [HIGHLIGHT_PROPERTY_NAMES.chapter]: { rich_text: {} },
  [HIGHLIGHT_PROPERTY_NAMES.color]: { select: {} },
  [HIGHLIGHT_PROPERTY_NAMES.annotatedAt]: { date: {} },
  [HIGHLIGHT_PROPERTY_NAMES.contentLimit]: { select: {} },
  [HIGHLIGHT_PROPERTY_NAMES.sourceHash]: { rich_text: {} },
  [HIGHLIGHT_PROPERTY_NAMES.sourceState]: { select: {} },
  [HIGHLIGHT_PROPERTY_NAMES.lastSynced]: { date: {} },
  [HIGHLIGHT_PROPERTY_NAMES.processStatus]: { select: {} },
  [HIGHLIGHT_PROPERTY_NAMES.importance]: { select: {} },
  [HIGHLIGHT_PROPERTY_NAMES.interpretation]: { rich_text: {} },
  [HIGHLIGHT_PROPERTY_NAMES.agreement]: { select: {} },
  [HIGHLIGHT_PROPERTY_NAMES.tags]: { multi_select: {} },
};
